x-database-variables: &database-variables
  POSTGRES_DB: ${POSTGRES_DB:-sourcetool_development}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

x-go-variables: &go-variables
  GOMODCACHE: /gomodcache

services:
  server:
    image: golang:1.23
    command: bash -c "
        go run ../devtools/cmd/db/main.go migrate ../migrations &&
        go run ./cmd/server"
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      <<: [*database-variables, *go-variables]
    env_file:
      - .env
    volumes:
      - ./backend/ee:/go/src/github.com/trysourcetool/sourcetool/backend/ee
      - ./backend:/go/src/github.com/trysourcetool/sourcetool/backend
      - ./proto:/go/src/github.com/trysourcetool/sourcetool/proto
      - gomodcache:/gomodcache
    working_dir: /go/src/github.com/trysourcetool/sourcetool/backend/ee

  frontend:
    image: node:20-alpine
    command: sh -c "yarn && yarn dev --host 0.0.0.0"
    ports:
      - 5173:5173
    depends_on:
      - server
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app

  postgres:
    image: postgres:15
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      <<: *database-variables
    volumes:
      - pgdata:/var/lib/postgresql/data:cached

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass password

volumes:
  pgdata:
  gomodcache:
  frontend_node_modules:
