x-database-variables: &database-variables
  POSTGRES_DB: ${POSTGRES_DB:-sourcetool_development}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

x-go-variables: &go-variables
  GOMODCACHE: /gomodcache

services:
  backend:
    image: golang:1.24
    command: bash -c "
      go run ./devtools/cmd/db/main.go migrate &&
      go run ./cmd/server"
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      <<: [*database-variables, *go-variables]
    env_file:
      - .env
    volumes:
      - ./backend:/go/src/github.com/trysourcetool/sourcetool/backend
      - gomodcache:/gomodcache
    working_dir: /go/src/github.com/trysourcetool/sourcetool/backend

  frontend:
    image: node:20-alpine
    command: sh -c "npm install --global corepack@latest && corepack enable && pnpm install --frozen-lockfile && pnpm dev:frontend --host 0.0.0.0 && pnpm dev:frontend:tsr"
    ports:
      - 5173:5173
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    working_dir: /app

  nginx:
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:15
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      <<: *database-variables
    volumes:
      - pgdata:/var/lib/postgresql/data:cached

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass password

volumes:
  pgdata:
  gomodcache:
  frontend_node_modules:
