packages:
  - frontend
  - docs
  - mcp/docs-mcp-server
  - sdk/node
  - examples/node/*

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0

catalog:
  clsx: ^2.1.1
  typescript: ^5.8.3
  vitest: ^3.1.1
  zod: ^3.24.2

publicHoistPattern:
  - '*eslint*'

overrides:
  '@sourcetool/node': link:sdk/node
