services:
  server:
    build:
      context: ..
      dockerfile: ./backend/cmd/server/Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - sourcetool_server_default
  postgres:
    image: postgres:15
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sourcetool_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:cached
    networks:
      - sourcetool_server_default
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    networks:
      - sourcetool_server_default

networks:
  sourcetool_server_default:
    external: true
