// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file exception/v1/exception.proto (package exception.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file exception/v1/exception.proto.
 */
export const file_exception_v1_exception: GenFile = /*@__PURE__*/
  fileDesc("ChxleGNlcHRpb24vdjEvZXhjZXB0aW9uLnByb3RvEgxleGNlcHRpb24udjEiVAoJRXhjZXB0aW9uEg0KBXRpdGxlGAEgASgJEg8KB21lc3NhZ2UYAiABKAkSEwoLc3RhY2tfdHJhY2UYAyADKAkSEgoKc2Vzc2lvbl9pZBgEIAEoCULCAQoQY29tLmV4Y2VwdGlvbi52MUIORXhjZXB0aW9uUHJvdG9QAVpLZ2l0aHViLmNvbS90cnlzb3VyY2V0b29sL3NvdXJjZXRvb2wtZ28vaW50ZXJuYWwvcGIvZXhjZXB0aW9uL3YxO2V4Y2VwdGlvbnYxogIDRVhYqgIMRXhjZXB0aW9uLlYxygINRXhjZXB0aW9uX1xWMeICGUV4Y2VwdGlvbl9cVjFcR1BCTWV0YWRhdGHqAg1FeGNlcHRpb246OlYxYgZwcm90bzM");

/**
 * @generated from message exception.v1.Exception
 */
export type Exception = Message<"exception.v1.Exception"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated string stack_trace = 3;
   */
  stackTrace: string[];

  /**
   * @generated from field: string session_id = 4;
   */
  sessionId: string;
};

/**
 * JSON type for the message exception.v1.Exception.
 */
export type ExceptionJson = {
  /**
   * @generated from field: string title = 1;
   */
  title?: string;

  /**
   * @generated from field: string message = 2;
   */
  message?: string;

  /**
   * @generated from field: repeated string stack_trace = 3;
   */
  stackTrace?: string[];

  /**
   * @generated from field: string session_id = 4;
   */
  sessionId?: string;
};

/**
 * Describes the message exception.v1.Exception.
 * Use `create(ExceptionSchema)` to create a new message.
 */
export const ExceptionSchema: GenMessage<Exception, ExceptionJson> = /*@__PURE__*/
  messageDesc(file_exception_v1_exception, 0);

