timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'website/app.yaml'
      - '--quiet'
    timeout: '1600s'