name: NPM Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate code
        run: make generate

      - name: Install dependencies
        working-directory: ts
        run: npm ci

      - name: Build package
        working-directory: ts
        run: npm run build

      - name: Create package tarball
        working-directory: ts
        run: npm pack

      - name: Publish to npm
        working-directory: ts
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
