timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'COMMIT_SHA=${COMMIT_SHA}'
    - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
    - 'VITE_DOMAIN=${_VITE_DOMAIN}'
    - 'DEPLOY_ENV=${_DEPLOY_ENV}'
    - 'REGION=${_REGION}'
    - 'SERVICE_NAME=sourcetool'

steps:
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: sh
    args:
      - -c
      - deploy/cloud/build.sh

  - id: deploy
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: sh
    args:
      - -c
      - deploy/cloud/deploy.sh
    waitFor: ['build']

service_account: '${_SERVICE_ACCOUNT}'