// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file agent/v1/agent.proto (package agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file agent/v1/agent.proto.
 */
export const file_agent_v1_agent: GenFile = /*@__PURE__*/
  fileDesc("ChRhZ2VudC92MS9hZ2VudC5wcm90bxIIYWdlbnQudjEiigEKBUFnZW50EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSFAoMaW5zdHJ1Y3Rpb25zGAQgASgJEg0KBW1vZGVsGAUgASgJEg4KBmdyb3VwcxgGIAMoCRIdCgV0b29scxgHIAMoCzIOLmFnZW50LnYxLlRvb2wiKQoEVG9vbBIMCgRuYW1lGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJQlsKDGNvbS5hZ2VudC52MUIKQWdlbnRQcm90b1ABogIDQVhYqgIIQWdlbnQuVjHKAghBZ2VudFxWMeICFEFnZW50XFYxXEdQQk1ldGFkYXRh6gIJQWdlbnQ6OlYxYgZwcm90bzM");

/**
 * @generated from message agent.v1.Agent
 */
export type Agent = Message<"agent.v1.Agent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string instructions = 4;
   */
  instructions: string;

  /**
   * @generated from field: string model = 5;
   */
  model: string;

  /**
   * @generated from field: repeated string groups = 6;
   */
  groups: string[];

  /**
   * @generated from field: repeated agent.v1.Tool tools = 7;
   */
  tools: Tool[];
};

/**
 * JSON type for the message agent.v1.Agent.
 */
export type AgentJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * @generated from field: string instructions = 4;
   */
  instructions?: string;

  /**
   * @generated from field: string model = 5;
   */
  model?: string;

  /**
   * @generated from field: repeated string groups = 6;
   */
  groups?: string[];

  /**
   * @generated from field: repeated agent.v1.Tool tools = 7;
   */
  tools?: ToolJson[];
};

/**
 * Describes the message agent.v1.Agent.
 * Use `create(AgentSchema)` to create a new message.
 */
export const AgentSchema: GenMessage<Agent, AgentJson> = /*@__PURE__*/
  messageDesc(file_agent_v1_agent, 0);

/**
 * @generated from message agent.v1.Tool
 */
export type Tool = Message<"agent.v1.Tool"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * JSON type for the message agent.v1.Tool.
 */
export type ToolJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: string description = 2;
   */
  description?: string;
};

/**
 * Describes the message agent.v1.Tool.
 * Use `create(ToolSchema)` to create a new message.
 */
export const ToolSchema: GenMessage<Tool, ToolJson> = /*@__PURE__*/
  messageDesc(file_agent_v1_agent, 1);

