// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file exception/v1/exception.proto (package sourcetool.exception.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file exception/v1/exception.proto.
 */
export const file_exception_v1_exception: GenFile = /*@__PURE__*/
  fileDesc("ChxleGNlcHRpb24vdjEvZXhjZXB0aW9uLnByb3RvEhdzb3VyY2V0b29sLmV4Y2VwdGlvbi52MSJUCglFeGNlcHRpb24SDQoFdGl0bGUYASABKAkSDwoHbWVzc2FnZRgCIAEoCRITCgtzdGFja190cmFjZRgDIAMoCRISCgpzZXNzaW9uX2lkGAQgASgJQvQBChtjb20uc291cmNldG9vbC5leGNlcHRpb24udjFCDkV4Y2VwdGlvblByb3RvUAFaRWdpdGh1Yi5jb20vdHJ5c291cmNldG9vbC9zb3VyY2V0b29sL3Byb3RvL2dvL2V4Y2VwdGlvbi92MTtleGNlcHRpb252MaICA1NFWKoCF1NvdXJjZXRvb2wuRXhjZXB0aW9uLlYxygIYU291cmNldG9vbFxFeGNlcHRpb25fXFYx4gIkU291cmNldG9vbFxFeGNlcHRpb25fXFYxXEdQQk1ldGFkYXRh6gIZU291cmNldG9vbDo6RXhjZXB0aW9uOjpWMWIGcHJvdG8z");

/**
 * @generated from message sourcetool.exception.v1.Exception
 */
export type Exception = Message<"sourcetool.exception.v1.Exception"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated string stack_trace = 3;
   */
  stackTrace: string[];

  /**
   * @generated from field: string session_id = 4;
   */
  sessionId: string;
};

/**
 * JSON type for the message sourcetool.exception.v1.Exception.
 */
export type ExceptionJson = {
  /**
   * @generated from field: string title = 1;
   */
  title?: string;

  /**
   * @generated from field: string message = 2;
   */
  message?: string;

  /**
   * @generated from field: repeated string stack_trace = 3;
   */
  stackTrace?: string[];

  /**
   * @generated from field: string session_id = 4;
   */
  sessionId?: string;
};

/**
 * Describes the message sourcetool.exception.v1.Exception.
 * Use `create(ExceptionSchema)` to create a new message.
 */
export const ExceptionSchema: GenMessage<Exception, ExceptionJson> = /*@__PURE__*/
  messageDesc(file_exception_v1_exception, 0);

