// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file redis/v1/redis.proto (package redis.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file redis/v1/redis.proto.
 */
export const file_redis_v1_redis: GenFile = /*@__PURE__*/
  fileDesc("ChRyZWRpcy92MS9yZWRpcy5wcm90bxIIcmVkaXMudjEiKwoMUmVkaXNNZXNzYWdlEgoKAmlkGAEgASgJEg8KB3BheWxvYWQYAiABKAxCoAEKDGNvbS5yZWRpcy52MUIKUmVkaXNQcm90b1ABWkNnaXRodWIuY29tL3RyeXNvdXJjZXRvb2wvc291cmNldG9vbC1nby9pbnRlcm5hbC9wYi9yZWRpcy92MTtyZWRpc3YxogIDUlhYqgIIUmVkaXMuVjHKAghSZWRpc1xWMeICFFJlZGlzXFYxXEdQQk1ldGFkYXRh6gIJUmVkaXM6OlYxYgZwcm90bzM");

/**
 * @generated from message redis.v1.RedisMessage
 */
export type RedisMessage = Message<"redis.v1.RedisMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * JSON type for the message redis.v1.RedisMessage.
 */
export type RedisMessageJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload?: string;
};

/**
 * Describes the message redis.v1.RedisMessage.
 * Use `create(RedisMessageSchema)` to create a new message.
 */
export const RedisMessageSchema: GenMessage<RedisMessage, RedisMessageJson> = /*@__PURE__*/
  messageDesc(file_redis_v1_redis, 0);

