// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file redis/v1/redis.proto (package sourcetool.redis.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file redis/v1/redis.proto.
 */
export const file_redis_v1_redis: GenFile = /*@__PURE__*/
  fileDesc("ChRyZWRpcy92MS9yZWRpcy5wcm90bxITc291cmNldG9vbC5yZWRpcy52MSIrCgxSZWRpc01lc3NhZ2USCgoCaWQYASABKAkSDwoHcGF5bG9hZBgCIAEoDELSAQoXY29tLnNvdXJjZXRvb2wucmVkaXMudjFCClJlZGlzUHJvdG9QAVo9Z2l0aHViLmNvbS90cnlzb3VyY2V0b29sL3NvdXJjZXRvb2wvcHJvdG8vZ28vcmVkaXMvdjE7cmVkaXN2MaICA1NSWKoCE1NvdXJjZXRvb2wuUmVkaXMuVjHKAhNTb3VyY2V0b29sXFJlZGlzXFYx4gIfU291cmNldG9vbFxSZWRpc1xWMVxHUEJNZXRhZGF0YeoCFVNvdXJjZXRvb2w6OlJlZGlzOjpWMWIGcHJvdG8z");

/**
 * @generated from message sourcetool.redis.v1.RedisMessage
 */
export type RedisMessage = Message<"sourcetool.redis.v1.RedisMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * JSON type for the message sourcetool.redis.v1.RedisMessage.
 */
export type RedisMessageJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload?: string;
};

/**
 * Describes the message sourcetool.redis.v1.RedisMessage.
 * Use `create(RedisMessageSchema)` to create a new message.
 */
export const RedisMessageSchema: GenMessage<RedisMessage, RedisMessageJson> = /*@__PURE__*/
  messageDesc(file_redis_v1_redis, 0);

