runtime: python39
service: default
env: standard
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  min_idle_instances: automatic
  max_idle_instances: automatic
  target_cpu_utilization: 0.65

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|webmanifest))$
    static_files: \1
    upload: .*\.(js|css|png|jpg|jpeg|gif|ico|svg|webmanifest)$
    secure: always
    http_headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff

  - url: /assets/(.*)
    static_files: assets/\1
    upload: assets/(.*)
    secure: always
    http_headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff