name: Backend Lint

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'
      - '!backend/README.md'

jobs:
  lint:
    name: Run backend linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.7
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run backend linters
        run: make backend-lint 