name: Go SDK Lint

on:
  pull_request:
    paths:
      - 'sdk/go/**'
      - '.github/workflows/go-sdk-lint.yml'
      - '!sdk/go/README.md'
      - '!sdk/go/MIRROR_README.md'
      - '!sdk/go/LICENSE'
      - '!sdk/go/SECURITY.md'
      - '!sdk/go/CODE_OF_CONDUCT.md'

jobs:
  lint:
    name: Run Go SDK linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.7
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run Go SDK linters
        run: make go-sdk-lint 