name: NPM Publish

on:
  push:
    branches:
      - main
    paths:
      - 'proto/ts/package.json'

jobs:
  check-version-change:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check
        run: ./devtools/check_proto_version_change.sh

  publish:
    # This job depends on the check-version-change job
    needs: check-version-change
    
    # Only run this job if the version_changed output from the previous job is 'true'
    # This is how we conditionally run the publish job only when the version has changed
    if: needs.check-version-change.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate code
        working-directory: proto
        run: make generate

      - name: Install dependencies
        working-directory: proto/ts
        run: npm ci

      - name: Build package
        working-directory: proto/ts
        run: npm run build

      - name: Create package tarball
        working-directory: proto/ts
        run: npm pack

      - name: Publish to npm
        working-directory: proto/ts
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
